AWSTemplateFormatVersion: '2010-09-09'

Description: Creates DMS resources

Parameters:
  #################################################
  # General
  #################################################
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - qa
      - prod

  ProjectName:
    Type: String
    Default: aws-dms-lab
    MinLength: 3
    MaxLength: 30
    AllowedPattern: '^[a-zA-Z0-9-]+$'

  #################################################
  # Networking
  #################################################
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where DMS will be deployed.

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: At least two subnets in different Availability Zones.

  #################################################
  # Replication Instance
  #################################################
  ReplicationInstanceClass:
    Type: String
    Default: dms.t3.medium
    AllowedValues:
      - dms.t3.micro
      - dms.t3.small
      - dms.t3.medium
      - dms.t3.large

  AllocatedStorage:
    Type: Number
    Default: 50
    MinValue: 20
    MaxValue: 6144

  MultiAZ:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  PubliclyAccessible:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

  #################################################
  # Source Database
  #################################################
  SourceServerName:
    Type: String
    Description: ngrok TCP endpoint hostname.

  SourcePort:
    Type: Number
    Default: 3306

  SourceDatabase:
    Type: String
    Default: company

  SourceUsername:
    Type: String
    Default: dms

  SourcePassword:
    Type: String
    NoEcho: true

  #################################################
  # Migration
  #################################################
  MigrationType:
    Type: String
    Default: full-load-and-cdc
    AllowedValues:
      - full-load
      - cdc
      - full-load-and-cdc

  EnableCloudWatchLogs:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  
  AuroraStackName:
    Type: String
    Default: aws-dms-lab-aurora
    Description: Name of the deployed Aurora CloudFormation stack.
  
  TargetUsername:
    Type: String
    Description: Aurora master username.
    Default: admin

  TargetPassword:
    Type: String
    Description: Aurora master password.
    NoEcho: true

Conditions:

  MultiAZCondition: !Equals
    - !Ref MultiAZ
    - "true"

  PublicAccessCondition: !Equals
    - !Ref PubliclyAccessible
    - "true"

  EnableCloudWatchLogsCondition: !Equals
    - !Ref EnableCloudWatchLogs
    - "true"

Resources:
  #################################################
  # DMS Replication Subnet Group
  #################################################
  DMSReplicationSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    Properties:
      ReplicationSubnetGroupIdentifier: !Sub "${ProjectName}-${Environment}-dms-subnet-group"
      ReplicationSubnetGroupDescription: DMS Replication Subnet Group
      SubnetIds: !Ref SubnetIds
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${ProjectName}-${Environment}-dms-subnet-group"
      #   - Key: Project
      #     Value: !Ref ProjectName
      #   - Key: Environment
      #     Value: !Ref Environment
      #   - Key: ManagedBy
      #     Value: CloudFormation
  
  #################################################
  # DMS Security Group
  #################################################
  DMSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for AWS DMS
      GroupName: !Sub "${ProjectName}-${Environment}-dms-sg"
      VpcId: !Ref VpcId
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${ProjectName}-${Environment}-dms-sg"
      #   - Key: Project
      #     Value: !Ref ProjectName
      #   - Key: Environment
      #     Value: !Ref Environment
      #   - Key: ManagedBy
      #     Value: CloudFormation

  #################################################
  # DMS Replication Instance
  #################################################
  DMSReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties:
      #################################################
      # Identifier
      #################################################
      ReplicationInstanceIdentifier: !Sub "${ProjectName}-${Environment}-dms"
      #################################################
      # Capacity
      #################################################
      ReplicationInstanceClass: !Ref ReplicationInstanceClass
      AllocatedStorage: !Ref AllocatedStorage
      #################################################
      # Networking
      #################################################
      ReplicationSubnetGroupIdentifier: !Ref DMSReplicationSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DMSSecurityGroup
      PubliclyAccessible: !If
        - PublicAccessCondition
        - true
        - false
      MultiAZ: !If
        - MultiAZCondition
        - true
        - false
      #################################################
      # Maintenance
      #################################################
      AutoMinorVersionUpgrade: true
      #################################################
      # Tags
      #################################################
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${ProjectName}-${Environment}-dms"
      #   - Key: Project
      #     Value: !Ref ProjectName
      #   - Key: Environment
      #     Value: !Ref Environment
      #   - Key: ManagedBy
      #     Value: CloudFormation
  
  #################################################
  # DMS Source Endpoint
  #################################################
  DMSSourceEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      #################################################
      # General
      #################################################
      EndpointIdentifier: !Sub "${ProjectName}-${Environment}-source"
      EndpointType: source
      EngineName: mysql
      #################################################
      # Connection
      #################################################
      ServerName: !Ref SourceServerName
      Port: !Ref SourcePort
      DatabaseName: !Ref SourceDatabase
      Username: !Ref SourceUsername
      Password: !Ref SourcePassword
      #################################################
      # MySQL Settings
      #################################################
      MySqlSettings:
        AfterConnectScript: "SET time_zone='+00:00';"
        EventsPollInterval: 5
        MaxFileSize: 32768
      #################################################
      # Tags
      #################################################
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${ProjectName}-${Environment}-source"
      #   - Key: Project
      #     Value: !Ref ProjectName
      #   - Key: Environment
      #     Value: !Ref Environment
      #   - Key: ManagedBy
      #     Value: CloudFormation

  #################################################
  # DMS Target Endpoint
  #################################################
  DMSTargetEndpoint:
    Type: AWS::DMS::Endpoint
    Properties:
      EndpointIdentifier: !Sub "${ProjectName}-${Environment}-target"
      EndpointType: target
      EngineName: aurora
      ServerName:
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-ClusterEndpoint"
      Port:
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-Port"
      DatabaseName:
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DatabaseName"
      Username: !Ref TargetUsername
      Password: !Ref TargetPassword
      # Tags:
      #   - Key: Name
      #     Value: !Sub "${ProjectName}-${Environment}-target"
      #   - Key: Project
      #     Value: !Ref ProjectName
      #   - Key: Environment
      #     Value: !Ref Environment
      #   - Key: ManagedBy
      #     Value: CloudFormation

Outputs:

  DMSReplicationInstanceArn:
    Description: DMS Replication Instance ARN
    Value: !Ref DMSReplicationInstance
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DMSReplicationInstanceArn"
  
  SourceEndpointArn:
    Description: Source Endpoint ARN
    Value: !Ref DMSSourceEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-SourceEndpointArn"
  
  TargetEndpointArn:
    Description: Source Endpoint ARN
    Value: !Ref DMSTargetEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-TargetEndpointArn"